template: true
valuesFilePath: ./values.yml

resources:
 - name: d_repo
   type: GitRepo
   configuration:
    gitProvider: {{.Values.myRepo.gitProvider}}
    path: {{.Values.myRepo.path}}
    branches:
     include: docker_build
 - name: d_image
   type: Image
   configuration:
    sourceRepository: jfrogdockerbuild
    imageName: punchhdev.jfrog.io/jfrogdockerbuild/dimage
    imageTag: latest
    autoPull: true

pipelines:
 - name: pipeline_d
   steps:
    - name: docker_build
      type: DockerBuild
      configuration:
       affinityGroup: d_group
       dockerFileLocation: .
       dockerFileName: dockerfile.yml
       dockerImageName: punchhdev.jfrog.io/jfrogdockerbuild/dimage
       dockerImageTag: latest
       inputResources:
        - name: d_repo
       integrations:
        - name: test_docker_build
    
    - name: docker_push
      type: DockerPush
      configuration:
       affinityGroup: d_group
       targetRepository: jfrogdockerbuild
       integrations:
        - name: test_docker_build
       inputSteps:
        - name: docker_build 
       outputResources:
        - name: d_image
       
