template: true
valuesFilePath: ./values.yml

resources:
 - name: myrepo1
   type: GitRepo
   configuration:
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{.Values.myRepo.path}}
      branches:
       include: kanishk_jfrog_demo


pipelines:
 - name: test_pipeline
   configuration:
    runtime:
     type: image
     image:
       auto:
        language: go
        versions:
         - 1.12
   steps:
    - name: docker_build
      type: Bash
      configuration:
       inputResources:
        - name: myrepo1
      execution:
       onExecute:
        - pushd $res_myrepo1_resourcePath
        - python tag.py
        - python --version
