template: true
valuesFilePath: ./values.yml

resources:
 - name: myrepo
   type: GitRepo
   configuration:
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{.Values.myRepo.path}}
      branches:
       include: kanishk_jfrog_demo
 - name: docker_image
   type: image
   configuration:
    registry: kanishk_docker
    imageName: kanishkrajawat01/stats-service
    imageTag: latest
   


pipelines:
 - name: python_pipeline
   steps:
    - name: p1
      type: Bash
      configuration:
       inputResources:
        - name: myrepo
        - name: docker_image
       runtime:
         type: host
       environmentVariables:
        DOCKER_ACC: punchh
        DOCKER_REPO: shippable-stats-service
      execution:
       onExecute:
        - python --version
        - docker --version
        - pushd $res_myrepo_resourcePath
        - python test.py
        - user=$res_docker_image_registry_username
        - pass=$res_docker_image_registry_password
        - echo $user
        - echo $pass
        - docker login -u $user -p $pass
        - docker build -t $DOCKER_ACC/$DOCKER_REPO:latest .
        - docker push $DOCKER_ACC/$DOCKER_REPO:latest
