template: true
valuesFilePath: ./values.yml

resources:
 - name: myrepo
   type: GitRepo
   configuration:
      gitProvider: {{.Values.myRepo.gitProvider}}
      path: {{.Values.myRepo.path}}
      branches:
       include: kanishk_jfrog_demo
 - name: docker_image
   type: Image
   configuration:
    registry: test_docker_build
    sourceRepository: jfrogdockerbuild
    imageName: punchhdev.jfrog.io/jfrogdockerbuild/dimage2
    imageTag: latest
   


pipelines:
 - name: build_pipeline
   configuration:
    runtime:
     type: image
     image:
       auto:
        language: go
        versions:
         - 1.12
   steps:
    - name: docker_build
      type: host
      configuration:
       integrations:
        - name: test_docker_build
       inputResources:
        - name: myrepo
          branch: kanishk_jfrog_demo
       outputResources:
        - name: docker_image
      execution:
       onStart:
        - pwd
       onExecute:
        - |
            if ( [ $res_myrepo_branchName == "kanishk_jfrog_demo"] && [ $res_myrepo_isPullRequest == false])
            then 
             pushd $res_myrepo_resourcePath
             retry_command jfrog rt config --url $int_test_docker_build_url --user $int_test_docker_build_user --apikey $int_test_docker_build_apikey
             docker build -t $res_docker_image_imageName:latest -f dockerfile.yml .
             jfrog rt docker-push $res_docker_image_imageName:latest $res_docker_image_sourceRepository
            fi 
       onSucess:
        - |
            if ( [ $res_myrepo_branchName == "kanishk_jfrog_demo"] && [ $res_myrepo_isPullRequest == false])
            then
             #  shipctl put_resource_state_multi docker_image_event_webhook_service "versionName=$COMMIT sourceName=$DOCKER_ACC/$DOCKER_REPO buildNumber=$BUILD_NUMBER"
            fi
